#pragma once

#error "VANE: post_config.h IS being loaded"

#undef POINTING_DEVICE_TASK_THROTTLE_MS
#define POINTING_DEVICE_TASK_THROTTLE_MS 1

#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_TAPPING_TERM 200
#define CIRQUE_PINNACLE_TOUCH_DEBOUNCE 50

#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
